'use strict';
/**
 * importCryptoIdentity.js
 *
 * Imports X.509 identities generated by cryptogen into the Fabric SDK file-system wallet.
 * This script is used instead of Fabric CA enrollment when the network is bootstrapped
 * with cryptogen (the typical dev/test approach in Hyperledger Fabric).
 *
 * Design decision: We use cryptogen-generated certificates directly because:
 *   1. The test network uses cryptogen, not a running Fabric CA server.
 *   2. This avoids the need for a live CA endpoint and TLS certificates.
 *   3. Admin and User1 credentials are pre-generated in the 'organizations/' directory.
 *
 * Two identities are imported:
 *   - "admin"   → Admin@manufacturer.shipment.com (used for privileged operations)
 *   - "appUser" → User1@manufacturer.shipment.com (used by the REST API for invoke/query)
 *
 * Run once after the network is started: node importCryptoIdentity.js
 */

const { Wallets } = require('fabric-network');
const fs = require('fs');
const path = require('path');

/**
 * Reads the first file from a directory and returns its content as a UTF-8 string.
 * Cryptogen places private keys and certificates in directories with a single file
 * whose name is a hash, so we always read index [0].
 *
 * @param {string} dir - Absolute path to the directory containing the credential file.
 * @returns {string} File contents as a UTF-8 string.
 */
function readFirstFile(dir) {
  const filename = fs.readdirSync(dir)[0];
  return fs.readFileSync(path.join(dir, filename), 'utf8');
}

/**
 * Builds and stores an X.509 identity object in the SDK wallet.
 *
 * @param {object} wallet     - Fabric SDK FileSystemWallet instance.
 * @param {string} label      - Wallet key (e.g. "admin" or "appUser").
 * @param {string} mspId      - MSP identifier for the identity's organisation.
 * @param {string} certPEM    - PEM-encoded X.509 certificate.
 * @param {string} keyPEM     - PEM-encoded private key.
 */
async function storeIdentity(wallet, label, mspId, certPEM, keyPEM) {
  const identity = {
    credentials: { certificate: certPEM, privateKey: keyPEM },
    mspId,          // Ties the identity to the correct MSP / organisation
    type: 'X.509',  // Fabric SDK identity type for certificate-based auth
  };
  await wallet.put(label, identity);
  console.log(`Stored identity "${label}" (MSP: ${mspId})`);
}

/**
 * Main entry point.
 * Locates the cryptogen output for ManufacturerMSP, reads the Admin and User1
 * credentials, and imports them into the local file-system wallet.
 */
async function main() {
  // Resolve the wallet directory relative to this script's location
  const walletPath = path.join(__dirname, '..', 'wallet');
  const wallet = await Wallets.newFileSystemWallet(walletPath);
  console.log(`Wallet path: ${walletPath}`);

  // Base path to the Manufacturer org's crypto material produced by cryptogen
  const orgPath = path.resolve(
    __dirname, '..', '..', 'network', 'organizations',
    'peerOrganizations', 'manufacturer.shipment.com'
  );

  // ── Import Admin identity ──────────────────────────────────────────────────
  // Admin is used for channel/chaincode administration tasks and privileged
  // chaincode calls such as AuthorizeParticipant and RevokeParticipant.
  const adminBase = path.join(orgPath, 'users', 'Admin@manufacturer.shipment.com', 'msp');
  const adminKey  = readFirstFile(path.join(adminBase, 'keystore'));
  const adminCert = readFirstFile(path.join(adminBase, 'signcerts'));
  await storeIdentity(wallet, 'admin', 'ManufacturerMSP', adminCert, adminKey);

  // ── Import User1 as "appUser" ──────────────────────────────────────────────
  // appUser is the identity used by the Express REST API (app.js) for all
  // chaincode invoke and query operations on behalf of client requests.
  const userBase = path.join(orgPath, 'users', 'User1@manufacturer.shipment.com', 'msp');
  const userKey  = readFirstFile(path.join(userBase, 'keystore'));
  const userCert = readFirstFile(path.join(userBase, 'signcerts'));
  await storeIdentity(wallet, 'appUser', 'ManufacturerMSP', userCert, userKey);
}

// Execute and handle any fatal errors
main().catch(e => { console.error(e); process.exit(1); });
